version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - apt-get install python3.10
      - pip install -r requriment.txt
     
  build:
    commands:
      - echo Build started on `date`
      #- django-admin runserver 
  post_build:
    commands:
      - echo Build completed on `date`
#      - python3 manage.py runserver 0.0.0.0:8000
    finally:
      - python3 manage.py runserver 0.0.0.0:8090 & sleep 30
      
artifacts:
  files:
    - '**/*'
